# Generated by Django 6.0.6 on 2026-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('category', models.CharField(choices=[('テキスト学習', 'テキスト学習'), ('過去問演習', '過去問演習'), ('弱点補強', '弱点補強')], max_length=50, verbose_name='カテゴリ')),
                ('step_number', models.IntegerField(verbose_name='ステップ番号')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['step_number'],
            },
        ),
    ]
