# Generated by Django 6.0.6 on 2026-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_goal_task_due_date_task_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], default='中', max_length=10, verbose_name='重要度'),
        ),
    ]
