# Generated by Django 6.0.6 on 2026-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3', '★★★'), ('2', '★★'), ('1', '★')], default='2', max_length=10, verbose_name='重要度'),
        ),
    ]
